# Generated by Django 4.1.4 on 2022-12-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('noticias', '0002_noticias_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='categorias.categorias'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
