# Generated by Django 4.0.8 on 2022-12-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0003_noticias_categoria_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='categorias.categorias'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
