# Generated by Django 4.0.8 on 2022-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticias_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='bajada',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
